### ISSUE TITLE
Question Regarding parameter groups

### ISSUE THREAD

**Issue by wolstena** [cloudposse/terraform-aws-rds-cluster#12]
I have a question regarding parameter groups. I have tried a couple things but I have not been able to construct a list of parameters for aws_rds_cluster_parameter_group resource in the module. For example I would like to set,

character_set_client=utf8
character_set_connection=utf8

Do you have an example definition for cluster_paramparameters

Cheers

**Comment by wolstena** [comment]
Figured it out.

`variable "cluster_parameters" {
    type = "list"
    default = [
        {
            name = "character_set_client"
            value = "utf8"
        },
        {
            name = "character_set_connection"
            value = "utf8"
        },
        {
            name = "character_set_database"
            value = "utf8"
        },
        {
            name = "character_set_results"
            value = "utf8"
        },
        {
            name = "character_set_server"
            value = "utf8"
        },
        {
            name = "collation_connection"
            value = "uft8_bin"
        },
        {
            name = "collation_server"
            value = "uft8_bin"
        },
        {
            name = "lower_case_table_names"
            value = "1"
            apply_method = "pending-reboot"
        },
        {
            name  = "skip-character-set-client-handshake"
            value = "1"
            apply_method = "pending-reboot"
        }
    ]
}
`

**Comment by osterman** [comment]
Thanks @wolstena! Sorry that we couldn't help out faster. Thanks for contributing your solution. 

@aknysh we should update docs with an example.

**Comment by wolstena** [comment]
@osterman the module is fantastic. I've made a few modifications for our purposes. These may be of general use value. Have added a db parameter group resource.  And, for backwards compatibility, I modified the aws_rds_cluster definition. 

`vpc_security_group_ids          = ["${aws_security_group.default.id}","${var.security_groups}"]`

I'd also like to add the option to enable monitoring.  I'll submit a pull-request if your interested.

**Comment by osterman** [comment]
@wolstena that would be cool! @aknysh will review the PR, if you submit it. We should have an option to enable monitoring.

**Comment by aknysh** [comment]
@wolstena  please submit the PR.
we also will update `README` with your `cluster_parameters ` examples.
thanks a lot

**Comment by aknysh** [comment]
@wolstena 
we updated `README` with your examples and merged to master
https://github.com/cloudposse/terraform-aws-rds-cluster/releases/tag/0.3.3

thanks again for your contribution!
please submit a PR if you have more changes
