### ISSUE TITLE
db_port not working as expected

### ISSUE THREAD

**Issue by User-nehag** [cloudposse/terraform-aws-rds-cluster#120]
**db_port = 5454**
I have defined db_port value as 5454 in .hcl file but after applying, RDS Instances(reader and writer) are created with port 5432. 
I am using below RDS configuration
engine = "aurora-postgresql"
engine_version = "10.14"
cluster_family = "aurora-postgresql10"

**Comment by nitrocode** [comment]
Can you try something like this ?

```hcl
module "rds_cluster_aurora_postgres" {
  source = "cloudposse/rds-cluster/aws"
  # Cloud Posse recommends pinning every module to a specific version
  # version     = "x.x.x"

  name = "postgres"

  engine         = "aurora-postgresql"
  engine_version = "10.14"
  cluster_family = "aurora-postgresql10"
  db_port        = 5432
}
```
