### ISSUE TITLE
Add option for RDS/Aurora Managed Master Passwords via Secrets Manager

### ISSUE THREAD

**Issue by fabianf92** [cloudposse/terraform-aws-rds-cluster#166]
### Describe the Feature

We want to use RDS integration with secret manager so that master password will be managed by RDS and rotated by secret manager.
This option is available in [Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/rds_cluster) by using the variable `manage_master_user_password` :
`Set to true to allow RDS to manage the master user password in Secrets Manager. Cannot be set if master_password is provided.`
Currently the cloudposse module does not allow to enable this feature.

### Expected Behavior

The module allows to enable managed user password feature in RDS.

### Use Case

Managed secrets are more secure and easy to use.

### Describe Ideal Solution

- Add a variable to enable managed master user password option in RDS.
- Add output block that contains the the secret ARN (see `master_user_secret` reference in the terraform docs).

**Comment by rstml** [comment]
Any plans for this? This should be quite simple to add - just pass through 2 additional variables?
