### ISSUE TITLE
Cluster name and current stage

### ISSUE THREAD

**Issue by mike-zipit** [cloudposse/terraform-aws-rds-cluster#17]
Our goal was to setup a single-instance development database (1 cluster member), and then a production cluster that scaled as usage grew.

However, when we created a single node, the route53 record didn't include the stage, so it will conflict with our production cluster (when created)

If I set `name = "${var.stage}-${var.name}"`, then my cluster name is `zw-dev-dev-application` (which I can live with).

Should stage be in the route53 records?

**Comment by osterman** [comment]
Hey @mike-zipit! So we never share DNS zones across stages. For example, we'll use `prod.cloudposse.org` and `staging.cloudposse.org`. We do not recommend sticking production and staging resources in the same DNS zone for the reasons you mention. It's easy to *accidentally* clobber records during development. Moreover, dev, staging and production resources should never be in the same AWS account. =)

**Comment by osterman** [comment]
Since you're operating in the same AWS account, consider using our [`terraform-aws-route53-cluster-zone`](https://github.com/cloudposse/terraform-aws-route53-cluster-zone) module to provision a DNS zone for each stage.

**Comment by osterman** [comment]
Closing this issue for now. If you have any more questions related to this don't hesitate to reopen it.
