### ISSUE TITLE
enable_http_endpoint not working for serverlessv2 configurations

### ISSUE THREAD

**Issue by hragbalian** [cloudposse/terraform-aws-rds-cluster#193]
### Describe the Bug

When `instance_type` is "db.serverless" (for V2 serverless) the `engine_mode` does not accept the value "serverless", but this value is required to enable the Data API via `enable_http_endpoint` = true.  As a result, the co-condition only applies for serverless v1. 

### Expected Behavior

That 
```
...
instance_type` = "db.serverless"
enable_http_endpoint = true
...
```
would enable the Data API for serverless V2

### Steps to Reproduce

```
...
instance_type` = "db.serverless"
enable_http_endpoint = true
...
```

### Environment

OSX, M1

**Comment by jerowe** [comment]
+1 for this bug. I can't create a serverlessv2 with the data API enabled until this bug is fixed.
