### ISSUE TITLE
Unable to updgrade from Aurora Postgres 12.16 to Aurora Postgres 16.1

### ISSUE THREAD

**Issue by Digi-Deli** [cloudposse/terraform-aws-rds-cluster#227]
### Describe the Bug

Using module version 1.11.0 I am trying to upgrade Aurora Postgresql from 12.16 to 16.1. The module seems to create the parameter groups with version 16.1 and link these parameter groups to the instance which is still in version 12.16

Error from applying the configuration 

│ Error: updating RDS Cluster (arm-dev-prl-aurora-notify-db): InvalidParameterCombination: The Parameter Group ********-20240822122924421600000001 with DBParameterGroupFamily aurora-postgresql16 cannot be used for this instance. Please use a Parameter Group with DBParameterGroupFamily aurora-postgresql12
│       status code: 400, request id: ebc1c38c-3c38-4fd3-9dd4-a10e36baf884
│ 
│   with module.rds_cluster_aurora_postgres.aws_rds_cluster.primary[0],
│   on .terraform/modules/rds_cluster_aurora_postgres/main.tf line 71, in resource "aws_rds_cluster" "primary":
│   71: resource "aws_rds_cluster" "primary" { 

I have tried to upgrade to aurora postgresql 13 with same results

### Expected Behavior

After changing the configurations and running the apply command, have the cluster and its instances to be upgraded to Aurora PostgreSQL 16.1

### Steps to Reproduce

Change parameter
cluster_family = "aurora-postgresql16"

Run terraform plan -out plan
Run terraform apply plan

### Environment

- OS: OSX
- Version: 14.1.2
- Module version: 1.11.0
- Terraform Version: 1.8.3

**Comment by danaya01** [comment]
Hi there,

anything on this? It is blocking update to latest Aurora Postgresql using your module.

Kind regards

**Comment by kevcube** [comment]
@Digi-Deli @danaya01 I would recommend doing a bit of terraform surgery to get your upgrade out, because this is a more complicated situation with need for `create_before_destroy` and other terraform lifecycle management work.

If you manage to work it into the module please PR!

**Comment by danaya01** [comment]
Hi @kevcube 

I've got it working in the end using the module as is. This can be closed.

Thank you
