### ISSUE TITLE
Move Inline Security Group Rules to Resources

### ISSUE THREAD

**Issue by osterman** [cloudposse/terraform-aws-rds-cluster#24]
## what
Use `aws_security_group_rule` instead of inline rules

## why
* Inline security groups are a bad practice because it breaks idempotency if other callers add security group rules

**Comment by jhosteny** [comment]
I took a shot at this, as I wanted to use the default security group in this module downstream, by exporting it to an output (separate from the output list of security groups it is in). But, I ran into [this](https://github.com/hashicorp/terraform/pull/2376). The only non-disruptive way I can think of to handle this for now is to create a resource with a new name. While the default group is not currently exported, that will cause the list of security groups (via `aws_rds_cluster`) to change.
