### ISSUE TITLE
Consider making zone_id an optional parameter

### ISSUE THREAD

**Issue by sgzijl** [cloudposse/terraform-aws-rds-cluster#29]
Hi there,

I noticed that the `zone_id` parameter is mandatory. Although it is a nice to have friendly DNS names for RDS endpoints, this may cause issues when ssl connections are used. Perhaps, it's worth to consider making the `zone_id` parameter optional.

// Siert

**Comment by aknysh** [comment]
thanks @sgzijl 
addressed in https://github.com/cloudposse/terraform-aws-rds-cluster/pull/30
