### ISSUE TITLE
Dropping variable availability_zones ?

### ISSUE THREAD

**Issue by maartenvanderhoef** [cloudposse/terraform-aws-rds-cluster#35]
Hi,

`availability_zones` is EC2 classic, I believe that the module and the examples will get better if EC2 classic support is dropped. The current examples are mixing EC2 Classic params with VPC params.

```
availability_zones - (Optional) A list of EC2 Availability Zones that instances in the DB cluster can be created in
```

**Comment by osterman** [comment]
I agree. We should just drop support for classic and update examples accordingly.

**Comment by aknysh** [comment]
thanks @maartenvanderhoef 
addressed in https://github.com/cloudposse/terraform-aws-rds-cluster/pull/38
