### ISSUE TITLE
Data API for Aurora serverless

### ISSUE THREAD

**Issue by manishkpr** [cloudposse/terraform-aws-rds-cluster#51]
How to enable Data API ?

![image](https://media.amazonwebservices.com/blog/2019/rds_enable_data_api_1.png)

**Comment by goruha** [comment]
@manishkpr we can not enable this with terraform 
There is no such option https://www.terraform.io/docs/providers/aws/r/rds_cluster.html
I guess that's because `Data API` is still in beta

**Comment by bionicles** [comment]
enable_http_endpoint - (Optional) Enable HTTP endpoint (data API). Only valid when engine_mode is set to serverless.

**Comment by daniel-0-1** [comment]
Hi cloudposse, thanks for all the awesome modules!
It seems the Data API option is now available in Terraform, as bionicles pointed out, as `enable_http_endpoint`.
The addition of this option would be great.

**Comment by mariocoski** [comment]
Hello @cloudposse, amazing work you do for the community - big thanks! I created a [PR](https://github.com/cloudposse/terraform-aws-rds-cluster/pull/69) to enable the option above.. Running my forked master produces desired outcome:
<img width="627" alt="Screenshot 2020-06-14 at 13 25 06" src="https://user-images.githubusercontent.com/12540508/84593161-b2428580-ae42-11ea-84a2-e80d1d965418.png">
Thank you

**Comment by osterman** [comment]
Thanks! release cut.

**Comment by manishkpr** [comment]
Thanks, Great Job!
