### ISSUE TITLE
Error loading modules: module rds_cluster_aurora_mysql

### ISSUE THREAD

**Issue by sarathi190590** [cloudposse/terraform-aws-rds-cluster#55]
Error downloading modules: Error loading modules: module rds_cluster_aurora_mysql: Error parsing .terraform/modules/9ab520df0bb135021263cffe5f895638/main.tf: At 3:16: Unknown token: 3:16 IDENT var.namespace

**Comment by aknysh** [comment]
@sarathi190590 
you see the error when using the master branch of the module with terraform 0.11.
The master branch is already on TF 0.12.
Don't use master branch for stability, pin to a release.
The last release for TF 0.11 is 0.15.0
