### ISSUE TITLE
Count not evaluating properly for mysql aurora serverless

### ISSUE THREAD

**Issue by rewt** [cloudposse/terraform-aws-rds-cluster#61]
[`local.cluster_instance_count`](https://github.com/cloudposse/terraform-aws-rds-cluster/blob/d95acc14b67be60aa157791fe23c0a7e6a168a9d/main.tf#L87) fails to evaluate to `0` when specifying:
```
cluster_size          = 0
autoscaling_enabled   = false
```
and module still attempts to create resource https://github.com/cloudposse/terraform-aws-rds-cluster/blob/d95acc14b67be60aa157791fe23c0a7e6a168a9d/main.tf#L92

Additionally, specifying `false` for `var.enabled` is ineffective.  

So the enabled variable doesn't appear to be working?  How can cluster instance be disabled when using aurora serverless?

**Comment by osterman** [comment]
I think this might have been fixed in #69
