### ISSUE TITLE
Incorrect cluster_instance_count calculation when autoscaling_enabled = true 

### ISSUE THREAD

**Issue by bradflood** [cloudposse/terraform-aws-rds-cluster#63]
For Aurora, autoscaling only applies to read replicas.  However, the terraform code here does not support creation of an autoscaling group with one read replica. 
This seems related to https://github.com/cloudposse/terraform-aws-rds-cluster/issues/61, but is slightly different, I believe

The instance_count and cluster_instance_count calculations are not correct when autoscaling_enabled = true.

Steps to reproduce:
1) Create cluster with autoscaling_enabled = false (default) 
2) change autoscaling_enabled to true, and accept the default value for autoscaling_min_capacity (default: 1)

result: two new resources are created 
- resource "aws_appautoscaling_policy" "replicas"
- resource "aws_appautoscaling_target" "replicas"
and one resource is deleted
- resource "aws_rds_cluster_instance" "default"

The aws_rds_cluster_instance is deleted because the value for local.cluster_instance_count has changed from 2 (the default if autoscaling_enabled=false) to 1 (based on different logic when autoscaling_enabled=true.

I confirmed this by setting autoscaling_min_capacity to 2. With this value, the resource aws_rds_cluster_instance is unmodified. However, in this case, the number of read replicas created is 2

Potential fix:
min_instance_count     = var.autoscaling_enabled ? var.autoscaling_min_capacity **+1** : var.cluster_size

**Comment by sumeetshk** [comment]
Yes ,The cluster_size or the instance_count should be independent of autoscaling_min_capacity as autoscaling_min_capacity is automatically taken care of by AWS through the autoscaling policy.

For example, when autoscaling is enabled:
  If I specify:
    cluster_size = 2
    autoscaling_min_capacity = 1
  
  terraform creates only one instance even though cluster_size is set to 2 , 

  and if I specify:
    cluster_size = 2
    autoscaling_min_capacity = 2 

  terraform spins up 2 instances but AWS autoscaling policy immediately spins up one more instance, which is not desired. 

  This also breaks the terraform as it is not aware of the new instance that is created by AWS autoscaling policy. 

Fix:
Remove min_instance count and just keep 
locals {
  cluster_instance_count = var.enabled ? var.cluster_size : 0
}

**Comment by sumeetshk** [comment]
@aknysh Is there a way I can raise a PR for this?
