### ISSUE TITLE
Required variables

### ISSUE THREAD

**Issue by lortega** [cloudposse/terraform-aws-rds-cluster#7]
There's now were I could find the minimum variables needed for creating a cluster.

I believe the required are:
* vpc_id
* security_groups
* zone_id
* admin_password
* subnets

**Comment by aknysh** [comment]
@lortega  thank you for reviewing the module.
We will add a `README` file with some examples on how to use the module and minimum settings required.

**Comment by aknysh** [comment]
@lortega  we added usage examples and description in https://github.com/cloudposse/terraform-aws-rds-cluster/releases/tag/0.3.0

Please let us know if that answers your questions, and if you need any help.
