### ISSUE TITLE
Missing arguments

### ISSUE THREAD

**Issue by hibbert** [cloudposse/terraform-aws-rds-cluster#71]
Found a bug? Maybe our [Slack Community](https://slack.cloudposse.com) can help. 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Bug

Looking at https://www.terraform.io/docs/providers/aws/r/rds_cluster.html and https://www.terraform.io/docs/providers/aws/r/rds_cluster_instance.html the following arguments are missing:

aws_rds_cluster - missing arguments:

availability_zones 
cluster_identifier_prefix 
db_subnet_group_name 
port

rds_cluster_instance - missing arguments:

identifier_prefix
apply_immediately
promotion_tier
preferred_backup_window
preferred_maintenance_window
auto_minor_version_upgrade 
copy_tags_to_snapshot 
ca_cert_identifier

## Expected Behavior

Arguments included and configurable if necessary

**Comment by jamengual** [comment]
We are happy to receive PR to add arguments but keep in mind that some arguments require other arguments and configs to be passed on and that is why the module does not expose every single one of them.
This is not a bug this is intentionally opinionated.
